export const DramaMoviesDatabase =[
    {
        Actors: "Frances McDormand, David Strathairn, Linda May",
Awards: "Won 3 Oscars. 233 wins & 139 nominations total",
BoxOffice: "$2,143,000",
Country: "United States",
DVD: "19 Feb 2021",
Director: "Chloé Zhao",
Genre: "Drama",
Language: "English",
Metascore: "93",
Plot: "A woman in her sixties, after losing everything in the Great Recession, embarks on a journey through the American West, living as a van-dwelling modern-day nomad.",
Poster: "https://m.media-amazon.com/images/M/MV5BMDRiZWUxNmItNDU5Yy00ODNmLTk0M2ItZjQzZTA5OTJkZjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
Production: "N/A",
Rated: "R",
Ratings: [
 {
Source: "Internet Movie Database",
Value: "7.4/10" ,},
{Source: "Rotten Tomatoes",
Value: "93%",
 },{
Source: "Metacritic",
Value: "93/100" ,},],
Released: "19 Feb 2021",
Response: "True",
Runtime: "107 min",
Title: "Nomadland",
Type: "movie",
Website: "N/A",
Writer: "Chloé Zhao, Jessica Bruder",
Year: "2020",
imdbID: "tt9770150",
imdbRating: "7.4",
imdbVotes: "126,127",
    },

    {
        Actors: "Riz Ahmed, Olivia Cooke, Paul Raci",
        Awards: "Won 2 Oscars. 82 wins & 163 nominations total",
        BoxOffice: "N/A",
        Country: "United States",
        DVD: "N/A",
        Director: "Darius Marder",
        Genre: "Drama, Music",
        Language: "English, American Sign , French",
        Metascore: "82",
        Plot: "A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNjcyYjg0M2ItMzMyZS00NmM1LTlhZDMtN2MxN2RhNWY4YTkwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
        Production: "Caviar",
        Rated: "R",
        Ratings: [
         {
        Source: "Internet Movie Database",
        Value: "7.8/10" },
        {Source: "Rotten Tomatoes",
        Value: "97%",
        },{
        Source: "Metacritic",
        Value: "82/100", },],
        Released: "04 Dec 2020",
        Response: "True",
        Runtime: "120 min",
        Title: "Sound of Metal",
        Type: "movie",
        Website: "N/A",
        Writer: "Darius Marder, Abraham Marder, Derek Cianfrance",
        Year: "2019",
        imdbID: "tt5363618",
        imdbRating: "7.8",
        imdbVotes: "104,647",
    },
     
    
    {
        Actors: "Dev Patel, Alicia Vikander, Joel Edgerton",
        Awards: "1 nomination",
        BoxOffice: "$17,173,321",
        Country: "Ireland, Canada, United States, United Kingdom",
        DVD: "19 Aug 2021",
        Director: "David Lowery",
        Genre: "Adventure, Drama, Fantasy",
        Language: "English",
        Metascore: "85",
        Plot: "A fantasy retelling of the medieval story of Sir Gawain and the Green Knight.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjMxNTdiNWMtOWY0My00MjM4LTkwNzMtOGI0YThhN2Q4M2I4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:
        [
            {
        Source: "Internet Movie Database",
        Value: "6.7/10" },

        {Source: "Rotten Tomatoes",
        Value: "88%",
         },{
        Source: "Metacritic",
        Value: "85/100", },],
        Released: "30 Jul 2021",
        Response: "True",
        Runtime: "130 min",
        Title: "The Green Knight",
        Type: "movie",
        Website: "N/A",
        Writer: "David Lowery",
        Year: "2021",
        imdbID: "tt9243804",
        imdbRating: "6.7",
        imdbVotes: "50,288",
    },
     
    ////3
    {
        Actors: "Jodie Foster, Matthew McConaughey, Tom Skerritt",
        Awards: "Nominated for 1 Oscar. 14 wins & 31 nominations total",
        BoxOffice: "$100,920,329",
        Country: "United States",
        DVD: "16 Dec 1997",
        Director: "Robert Zemeckis",
        Genre: "Drama, Mystery, Sci-Fi",
        Language: "English, Spanish, German, Russian",
        Metascore: "62",
        Plot: "Dr. Ellie Arroway, after years of searching, finds conclusive radio proof of extraterrestrial intelligence, sending plans for a mysterious machine.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYWNkYmFiZjUtYmI3Ni00NzIwLTkxZjktN2ZkMjdhMzlkMDc3XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG",
        Ratings:  
[        {Source: "Internet Movie Database",
        Value: "7.5/10" ,},
       { Source: "Rotten Tomatoes",
        Value: "66%",
         }
         ,{
        Source: "Metacritic",
        Value: "62/100" ,},],
        Released: "11 Jul 1997",
        Response: "True",
        Runtime: "150 min",
        Title: "Contact",
        Type: "movie",
        Website: "N/A",
        Writer: "James V. Hart, Michael Goldenberg, Carl Sagan",
        Year: "1997",
        imdbID: "tt0118884",
        imdbRating: "7.5",
        imdbVotes: "263,399",
    },
     
    ///4
    {
        Actors: "Tom Holland, Bill Skarsgård, Riley Keough",
        Awards: "3 nominations",
        BoxOffice: "N/A",
        Country: "United States",
        DVD: "16 Sep 2020",
        Director: "Antonio Campos",
        Genre: "Crime, Drama, Thriller",
        Language: "English",
        Metascore: "55",
        Plot: "Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.",
        Poster: "https://m.media-amazon.com/images/M/MV5BZmE1NmVmN2EtMjZmZC00YzAyLWE4MWEtYjY5YmExMjUxODU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
         {
        Source: "Internet Movie Database",
        Value: "7.1/10" },
        {Source: "Rotten Tomatoes",
        Value: "64%",
         },{
        Source: "Metacritic",
        Value: "55/100" ,},],
        Released: "16 Sep 2020",
        Response: "True",
        Runtime: "138 min",
        Title: "The Devil All the Time",
        Type: "movie",
        Website: "N/A",
        Writer: "Antonio Campos, Paulo Campos, Donald Ray Pollock",
        Year: "2020",
        imdbID: "tt7395114",
        imdbRating: "7.1",
        imdbVotes: "112,316",
    },
     
    
    {
        Actors: "Harrison Ford, Ryan Gosling, Ana de Armas",
        Awards: "Won 2 Oscars. 99 wins & 158 nominations total",
        BoxOffice: "$92,054,159",
        Country: "United States, United Kingdom, Canada, Hungary, Spain, Mexico",
        DVD: "16 Jan 2018",
        Director: "Denis Villeneuve",
        Genre: "Action, Drama, Mystery",
        Language: "English, Finnish, Japanese, Hungarian, Russian, Somali, Spanish",
        Metascore: "81",
        Plot: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:  [
            {
        Source: "Internet Movie Database",
        Value: "8.0/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "88%",
         },{
        Source: "Metacritic",
        Value: "81/100" ,},],
        Released: "06 Oct 2017",
        Response: "True",
        Runtime: "164 min",
        Title: "Blade Runner 2049",
        Type: "movie",
        Website: "N/A",
        Writer: "Hampton Fancher, Michael Green, Philip K. Dick",
        Year: "2017",
        imdbID: "tt1856101",
        imdbRating: "8.0",
        imdbVotes: "497,149",
    },
     
    ///6
    {
        Actors: "Denzel Washington, Rami Malek, Jared Leto",
        Awards: "2 nominations",
        BoxOffice: "$15,244,012",
        Country: "United States",
        DVD: "29 Jan 2021",
        Director: "John Lee Hancock",
        Genre: "Crime, Drama, Mystery",
        Language: "English",
        Metascore: "54",
        Plot: "Kern County Deputy Sheriff Joe Deacon is sent to Los Angeles for what should have been a quick evidence-gathering assignment. Instead, he becomes embroiled in the search for a serial killer who is terrorizing the city.",
        Poster: "https://m.media-amazon.com/images/M/MV5BOGFlNTdmYWQtM2IzMi00YTY3LTlmMDQtZDI5NGQ5MjYzZmEwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "6.3/10" },
        {Source: "Rotten Tomatoes",
        Value: "45%",
         },{
        Source: "Metacritic",
        Value: "54/100" ,},],
        Released: "29 Jan 2021",
        Response: "True",
        Runtime: "128 min",
        Title: "The Little Things",
        Type: "movie",
        Website: "N/A",
        Writer: "John Lee Hancock",
        Year: "2021",
        imdbID: "tt10016180",
        imdbRating: "6.3",
        imdbVotes: "76,555",
    },
     
    
    {
        Actors: "Mélanie Laurent, Mathieu Amalric, Malik Zidi",
        Awards: "N/A",
        BoxOffice: "N/A",
        Country: "France, United States",
        DVD: "12 May 2021",
        Director: "Alexandre Aja",
        Genre: "Drama, Fantasy, Sci-Fi",
        Language: "French",
        Metascore: "67",
        Plot: "A woman wakes in a cryogenic chamber with no recollection of how she got there. As she's running out of oxygen, she must rebuild her memory to find a way out of her nightmare.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMWQ3N2EzNjYtMzgwYS00YjdmLThmOTUtMzc4NDUxZjZkY2RhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "TV-14",
        Ratings: 
        [
            {
        Source: "Internet Movie Database",
        Value: "6.5/10" },
        {Source: "Rotten Tomatoes",
        Value: "88%",
         },{
        Source: "Metacritic",
        Value: "67/100" ,},],
        Released: "12 May 2021",
        Response: "True",
        Runtime: "100 min",
        Title: "Oxygène",
        Type: "movie",
        Website: "N/A",
        Writer: "Christie LeBlanc",
        Year: "2021",
        imdbID: "tt6341832",
        imdbRating: "6.5",
        imdbVotes: "30,964",
    },
     
    ///8
    {
        Actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
        Awards: "Nominated for 5 Oscars. 37 wins & 179 nominations total",
        BoxOffice: "$116,900,694",
        Country: "United States",
        DVD: "25 Mar 2014",
        Director: "Martin Scorsese",
        Genre: "Biography, Crime, Drama",
        Language: "English, French",
        Metascore: "75",
        Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: 
         [ 
            {
        Source: "Internet Movie Database",
        Value: "8.2/10" },

        {Source: "Rotten Tomatoes",
        Value: "79%",
         },{
        Source: "Metacritic",
        Value: "75/100" ,},],
        Released: "25 Dec 2013",
        Response: "True",
        Runtime: "180 min",
        Title: "The Wolf of Wall Street",
        Type: "movie",
        Website: "N/A",
        Writer: "Terence Winter, Jordan Belfort",
        Year: "2013",
        imdbID: "tt0993846",
        imdbRating: "8.2",
        imdbVotes: "1,263,780",
    },
     
    
    {
        Actors: "Eddie Redmayne, Alex Sharp, Sacha Baron Cohen",
        Awards: "Nominated for 6 Oscars. 56 wins & 187 nominations total",
        BoxOffice: "N/A",
        Country: "United States, United Kingdom, India",
        DVD: "16 Oct 2020",
        Director: "Aaron Sorkin",
        Genre: "Drama, History, Thriller",
        Language: "English, Latin, French",
        Metascore: "76",
        Plot: "The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention in Chicago, Illinois.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYjYzOGE1MjUtODgyMy00ZDAxLTljYTgtNzk0Njg2YWQwMTZhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: 
        [
            {
        Source: "Internet Movie Database",
        Value: "7.8/10" },
        {Source: "Rotten Tomatoes",
        Value: "89%",
         },{
        Source: "Metacritic",
        Value: "76/100" ,},],
        Released: "16 Oct 2020",
        Response: "True",
        Runtime: "129 min",
        Title: "The Trial of the Chicago 7",
        Type: "movie",
        Website: "N/A",
        Writer: "Aaron Sorkin",
        Year: "2020",
        imdbID: "tt1070874",
        imdbRating: "7.8",
        imdbVotes: "157,780",
    },
     
    
]