export const ActionMovieDatabase =[
    {
        Actors: "Melissa McCarthy, Octavia Spencer, Jason Bateman",
Awards: "2 nominations.",
BoxOffice: "N/A",
Country: "United States",
DVD: "09 Apr 2021",
Director: "Ben Falcone",
Genre: "Action, Adventure, Comedy",
Language: "English",
Metascore: "34",
Plot: "In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.",
Poster: "https://m.media-amazon.com/images/M/MV5BMWZkM2I2NjEtNWM0Mi00MTgwLWJlYTAtYmNkZWYzNmQ1ZTBiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
Production: "N/A",
Rated: "PG-13",
Ratings:[
{Source: "Internet Movie Database",
Value: "4.4/10"
 ,},{
Source: "Rotten Tomatoes",
Value: "21%" ,},],
Source: "Metacritic",
Value: "34/100",
Released: "09 Apr 2021",
Response: "True",
Runtime: "106 min",
Title: "Thunder Force",
Type: "movie",
Website: "N/A",
Writer: "Ben Falcone",
Year: "2021",
imdbID: "tt10121392",
imdbRating: "4.4",
imdbVotes: "37,437",
    },
    
    {
        Actors: "Lewis Tan, Jessica McNamee, Josh Lawson",
    Awards: "1 nomination.",
    BoxOffice: "$42,201,013",
    Country: "United States",
    DVD: "23 Apr 2021",
    Director: "Simon McQuoid",
    Genre: "Action, Adventure, Fantasy",
    Language: "English, Japanese, Chinese",
    Metascore: "44",
    Plot: "MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.",
    Poster: "https://m.media-amazon.com/images/M/MV5BY2ZlNWIxODMtN2YwZi00ZjNmLWIyN2UtZTFkYmZkNDQyNTAyXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg",
    Production: "N/A",
    Rated: "R",
    Ratings:  [
        {
Source: "Internet Movie Database",
Value: "6.1/10" ,},
{Source: "Rotten Tomatoes",
Value: "55%",
 },
 {
Source: "Metacritic",
Value: "44/100",},
    ],
    Released: "23 Apr 2021",
    Response: "True",
    Runtime: "110 min",
    Title: "Mortal Kombat",
    Type: "movie",
    Website: "N/A",
    Writer: "Greg Russo, Dave Callaham, Oren Uziel",
    Year: "2021",
    imdbID: "tt0293429",
    imdbRating: "6.1",
    imdbVotes: "139,996",

    },
    ///2
    {
        Actors: "Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall",
        Awards: "1 win & 1 nomination",
        BoxOffice: "$100,563,133",
        Country: "United States, Australia, Canada, India",
        DVD: "31 Mar 2021",
        Director: "Adam Wingard",
        Genre: "Action, Sci-Fi, Thriller",
        Language: "English, American Sign ",
        Metascore: "59",
        Plot: "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against one another - the fearsome Godzilla and the mighty Kong - with humanity caught in the balance.",
        Poster: "https://m.media-amazon.com/images/M/MV5BZmYzMzU4NjctNDI0Mi00MGExLWI3ZDQtYzQzYThmYzc2ZmNjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
        {
        Source: "Internet Movie Database",
        Value: "6.4/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "75%",
        },{
        Source: "Metacritic",
        Value: "59/100" ,},],
        Released: "31 Mar 2021",
        Response: "True",
        Runtime: "113 min",
        Title: "Godzilla vs. Kong",
        Type: "movie",
        Website: "N/A",
        Writer: "Terry Rossio, Michael Dougherty, Zach Shields",
        Year: "2021",
        imdbID: "tt5034838",
        imdbRating: "6.4",
        imdbVotes: "172,726",
    },
    {
    Actors: "Bob Odenkirk, Aleksey Serebryakov, Connie Nielsen",
Awards: "1 win & 2 nominations",
BoxOffice: "$27,268,035",
Country: "United States, Japan",
DVD: "15 Apr 2021",
Director: "Ilya Naishuller",
Genre: "Action, Crime, Drama",
Language: "English, Russian, Spanish",
Metascore: "64",
Plot: "A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.",
Poster: "https://m.media-amazon.com/images/M/MV5BMjM5YTRlZmUtZGVmYi00ZjE2LWIyNzAtOWVhMDk1MDdkYzhjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
Production: "N/A",
Rated: "R",
Ratings: [
{
Source: "Internet Movie Database",
Value: "7.4/10" ,},
{Source: "Rotten Tomatoes",
Value: "84%",
},{
Source: "Metacritic",
Value: "64/100" ,},],
Released: "26 Mar 2021",
Response: "True",
Runtime: "92 min",
Title: "Nobody",
Type: "movie",
Website: "N/A",
Writer: "Derek Kolstad",
Year: "2021",
imdbID: "tt7888964",
imdbRating: "7.4",
imdbVotes: "159,241",
    

    },
    ///4
    {
        Actors: "Henry Cavill, Ben Affleck, Gal Gadot",
        Awards: "2 nominations",
        BoxOffice: "N/A",
        Country: "United States, United Kingdom",
        DVD: "N/A",
        Director: "Zack Snyder",
        Genre: "Action, Adventure, Fantasy",
        Language: "English, Icelandic, French",
        Metascore: "54",
        Plot: "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYjI3NDg0ZTEtMDEwYS00YWMyLThjYjktMTNlM2NmYjc1OGRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
        
        {Source: "Internet Movie Database",
        Value: "8.1/10",
        },{
        Source: "Metacritic",
        Value: "54/100" ,},],
        Released: "18 Mar 2021",
        Response: "True",
        Runtime: "242 min",
        Title: "Zack Snyder's Justice League",
        Type: "movie",
        Website: "N/A",
        Writer: "Jerry Siegel, Joe Shuster, Zack Snyder",
        Year: "2021",
        imdbID: "tt12361974",
        imdbRating: "8.1",
        imdbVotes: "339,005",
    },
    
    {
        Actors: "Dylan O'Brien, Jessica Henwick, Michael Rooker",
        Awards: "Nominated for 1 Oscar. 4 nominations total",
        BoxOffice: "$1,070,714",
        Country: "Canada, United States, Australia",
        DVD: "16 Oct 2020",
        Director: "Michael Matthews",
        Genre: "Action, Adventure, Comedy",
        Language: "English",
        Metascore: "63",
        Plot: "Seven years after he survived the monster apocalypse, lovably hapless Joel leaves his cozy underground bunker behind on a quest to reunite with his ex.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYWVkMWEyMDUtZTVmOC00MTYxLWE1ZTUtNjk4M2IzMjY2OTIxXkEyXkFqcGdeQXVyMDk5Mzc5MQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings:  [
            {
        Source: "Internet Movie Database",
        Value: "7.0/10" ,},

        {Source: "Rotten Tomatoes",
        Value: "94%",
         },
         {
        Source: "Metacritic",
        Value: "63/100" },],
        Released: "16 Oct 2020",
        Response: "True",
        Runtime: "109 min",
        Title: "Love and Monsters",
        Type: "movie",
        Website: "N/A",
        Writer: "Brian Duffield, Matthew Robinson",
        Year: "2020",
        imdbID: "tt2222042",
        imdbRating: "7.0",
        imdbVotes: "106,997",
    },
    ///6
    {
        Actors: "Maisie Williams, Anya Taylor-Joy, Charlie Heaton",
        Awards: "4 nominations",
        BoxOffice: "$23,852,659",
        Country: "United States",
        DVD: "10 Oct 2020",
        Director: "Josh Boone",
        Genre: "Action, Horror, Mystery",
        Language: "English, Portuguese, Latin",
        Metascore: "43",
        Plot: "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.",
        Poster: "https://m.media-amazon.com/images/M/MV5BZDQ2NTdmNDgtMGIwMS00ODE2LTk5M2EtZGZhYzc4MWRlNTU3XkEyXkFqcGdeQXVyNTc4MjczMTM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
    
        {Source: "Internet Movie Database",
        Value: "5.3/10",
         },
        {Source: "Rotten Tomatoes",
        Value: "36%"
         },{
        Source: "Metacritic",
        Value: "43/100" ,}],
        Released: "28 Aug 2020",
        Response: "True",
        Runtime: "94 min",
        Title: "The New Mutants",
        Type: "movie",
        Website: "N/A",
        Writer: "Josh Boone, Knate Lee",
        Year: "2020",
        imdbID: "tt4682266",
        imdbRating: "5.3",
        imdbVotes: "65,838",
    },
    ///7
    {
        Actors: "Katheryn Winnick, Liam Neeson, Teresa Ruiz",
        Awards: "N/A",
        BoxOffice: "$15,566,093",
        Country: "United States",
        DVD: "23 Mar 2021",
        Director: "Robert Lorenz",
        Genre: "Action, Drama, Thriller",
        Language: "English, Spanish",
        Metascore: "44",
        Plot: "A rancher on the Arizona border becomes the unlikely defender of a young Mexican boy desperately fleeing the cartel assassins who've pursued him into the U.S.",
        Poster: "https://m.media-amazon.com/images/M/MV5BODdlNThhMTUtNmU1OS00ZjM3LWE1ZjMtOWViN2RhYWRiZTg5XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
        {
        Source: "Internet Movie Database",
        Value: "5.6/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "37%",
         },{
        Source: "Metacritic",
        Value: "44/100", },],
        Released: "15 Jan 2021",
        Response: "True",
        Runtime: "108 min",
        Title: "The Marksman",
        Type: "movie",
        Website: "N/A",
        Writer: "Chris Charles, Danny Kravitz, Robert Lorenz",
        Year: "2021",
        imdbID: "tt6902332",
        imdbRating: "5.6",
        imdbVotes: "22,643",
    },
    
    {
        Actors: "Margot Robbie, Idris Elba, John Cena",
        Awards: "N/A",
        BoxOffice: "$55,789,082",
        Country: "United States, Canada, United Kingdom",
        DVD: "N/A",
        Director: "James Gunn",
        Genre: "Action, Adventure, Comedy",
        Language: "English",
        Metascore: "72",
        Plot: "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNGM3YzdlOWYtNjViZS00MTE2LWE1MWUtZmE2ZTcxZjcyMmU3XkEyXkFqcGdeQXVyODEyMTI1MjA@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:  [ 
        {Source: "Internet Movie Database",
        Value: "7.3/10",
         },{
        Source: "Metacritic",
        Value: "72/100" ,},],
        Released: "05 Aug 2021",
        Response: "True",
        Runtime: "132 min",
        Title: "The Suicide Squad",
        Type: "movie",
        Website: "N/A",
        Writer: "James Gunn",
        Year: "2021",
        imdbID: "tt6334354",
        imdbRating: "7.3",
        imdbVotes: "219,449",
    },
    //9
    {
        Actors: "Tom Holland, Daisy Ridley, Demián Bichir",
        Awards: "2 nominations.",
        BoxOffice: "$13,287,908",
        Country: "United States, Canada, Hong Kong, Luxembourg",
        DVD: "02 Apr 2021",
        Director: "Doug Liman",
        Genre: "Action, Adventure, Fantasy",
        Language: "English",
        Metascore: "38",
        Plot: "Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality where all thoughts are seen and heard by everyone.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYTcxYTk3MWQtZThlMS00ZjQ0LTg0NjktNGVkNWM2MTAyYWJmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: 
        [
            {
        Source: "Internet Movie Database",
        Value: "5.7/10" },
        {Source: "Rotten Tomatoes",
        Value: "21%"
        ,},{
        Source: "Metacritic",
        Value: "38/100" ,},],
        Released: "05 Mar 2021",
        Response: "True",
        Runtime: "109 min",
        Title: "Chaos Walking",
        Type: "movie",
        Website: "N/A",
        Writer: "Patrick Ness, Christopher Ford",
        Year: "2021",
        imdbID: "tt2076822",
        imdbRating: "5.7",
        imdbVotes: "33,078",
    },
     
    
        
]