export const RomanceMovieDatabase = [
    {
        Actors: "Andy Samberg, Cristin Milioti, J.K. Simmons",
        Awards: "14 wins & 43 nominations",
        BoxOffice: "$164,000",
        Country: "United States, Hong Kong",
        DVD: "10 Jul 2020",
        Director: "Max Barbakow",
        Genre: "Comedy, Fantasy, Mystery",
        Language: "English",
        Metascore: "83",
        Plot: "Stuck in a time loop, two wedding guests develop a budding romance while living the same day over and over again.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYjk0MTgzMmQtZmY2My00NmE5LWExNGUtYjZkNTA3ZDkyMTJiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [ 
        {Source: "Internet Movie Database",
        Value: "7.4/10",
        },
        {Source: "Rotten Tomatoes",
        Value: "95%",
         },{
        Source: "Metacritic",
        Value: "83/100" ,},],
        Released: "10 Jul 2020",
        Response: "True",
        Runtime: "90 min",
        Title: "Palm Springs",
        Type: "movie",
        Website: "N/A",
        Writer: "Andy Siara, Max Barbakow",
        Year: "2020",
        imdbID: "tt9484998",
        imdbRating: "7.4",
        imdbVotes: "130,192",
    },

    {
        Actors: "Sebastian Stan, Denise Gough, Yorgos Pirpassopoulos",
        Awards: "N/A",
        BoxOffice: "$30,932",
        Country: "United Kingdom, United States, Greece",
        DVD: "16 Apr 2021",
        Director: "Argyris Papadimitropoulos",
        Genre: "Drama, Romance",
        Language: "English, Greek",
        Metascore: "58",
        Plot: "A spark on a Friday can lead to a sizzling weekend fling, but what happens when you get to the inevitable Monday?",
        Poster: "https://m.media-amazon.com/images/M/MV5BYTg4NWQ4ODEtMmQ3Zi00N2JlLTgzNDEtMDMzYjNkODUzODE5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "6.1/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "50%",
        },{
        Source: "Metacritic",
        Value: "58/100" },],
        Released: "16 Apr 2021",
        Response: "True",
        Runtime: "116 min",
        Title: "Monday",
        Type: "movie",
        Website: "N/A",
        Writer: "Rob Hayes, Argyris Papadimitropoulos",
        Year: "2020",
        imdbID: "tt8884906",
        imdbRating: "6.1",
        imdbVotes: "2,991",
    },
    ///2
    {
        Actors: "Leonardo DiCaprio, Kate Winslet, Billy Zane",
        Awards: "Won 11 Oscars. 125 wins & 83 nominations total",
        BoxOffice: "$659,363,944",
        Country: "United States, Mexico, Australia",
        DVD: "08 Jan 2002",
        Director: "James Cameron",
        Genre: "Drama, Romance",
        Language: "English, Swedish, Italian, French",
        Metascore: "75",
        Plot: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
        {Source: "Internet Movie Database",
        Value: "7.8/10",
         },
        {Source: "Rotten Tomatoes",
        Value: "89%",
         },{
        Source: "Metacritic",
        Value: "75/100" ,},],
        Released: "19 Dec 1997",
        Response: "True",
        Runtime: "194 min",
        Title: "Titanic",
        Type: "movie",
        Website: "N/A",
        Writer: "James Cameron",
        Year: "1997",
        imdbID: "tt0120338",
        imdbRating: "7.8",
        imdbVotes: "1,092,075",
    },
    ///3
    {
        Actors: "Ben Affleck, Kate Beckinsale, Josh Hartnett",
        Awards: "Won 1 Oscar. 14 wins & 51 nominations total",
        BoxOffice: "$198,542,554",
        Country: "United States",
        DVD: "24 Apr 2001",
        Director: "Michael Bay",
        Genre: "Action, Drama, History",
        Language: "English, Japanese, French",
        Metascore: "44",
        Plot: "A tale of war and romance mixed in with history. The story follows two lifelong friends and a beautiful nurse who are caught up in the horror of an infamous Sunday morning in 1941.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTQ3MDc0MDc1NF5BMl5BanBnXkFtZTYwODI1ODY2._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
         
       { Source: "Internet Movie Database",
        Value: "6.2/10",
         },
        {Source: "Rotten Tomatoes",
        Value: "24%",
         },
         {
        Source: "Metacritic",
        Value: "44/100" ,},],
        Released: "25 May 2001",
        Response: "True",
        Runtime: "183 min",
        Title: "Pearl Harbor",
        Type: "movie",
        Website: "N/A",
        Writer: "Randall Wallace",
        Year: "2001",
        imdbID: "tt0213149",
        imdbRating: "6.2",
        imdbVotes: "320,042",
    },
    
    {
        Actors: "Travis Tedford, Bug Hall, Brittany Ashton Holmes",
        Awards: "2 wins",
        BoxOffice: "$52,125,282",
        Country: "United States",
        DVD: "30 Apr 2004",
        Director: "Penelope Spheeris",
        Genre: "Comedy, Family, Romance",
        Language: "English",
        Metascore: "45",
        Plot: "Alfalfa is wooing Darla and his \"He-Man-Woman-Hating\" friends attempt to sabotage the relationship.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYWE1MzdmNmMtNWQwZS00MTVkLTk3MDMtYzVkOWZlOTczMDIwXkEyXkFqcGdeQXVyNjg4NzYzMzA@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG",
        Ratings:  [ 
        {Source: "Internet Movie Database",
        Value: "6.3/10",
         },
        {Source: "Rotten Tomatoes",
        Value: "23%"
         ,},{
        Source: "Metacritic",
        Value: "45/100" ,},],
        Released: "05 Aug 1994",
        Response: "True",
        Runtime: "82 min",
        Title: "The Little Rascals",
        Type: "movie",
        Website: "N/A",
        Writer: "Penelope Spheeris, Robert Wolterstorff, Mike Scott",
        Year: "1994",
        imdbID: "tt0110366",
        imdbRating: "6.3",
        imdbVotes: "46,597",
    },
    
    {
        Actors: "Hugh Grant, Andie MacDowell, James Fleet",
        Awards: "Nominated for 2 Oscars. 24 wins & 28 nominations total",
        BoxOffice: "$52,700,832",
        Country: "United Kingdom",
        DVD: "19 Dec 2000",
        Director: "Mike Newell",
        Genre: "Comedy, Drama, Romance",
        Language: "English, British Sign ",
        Metascore: "81",
        Plot: "Over the course of five social occasions, a committed bachelor must consider the notion that he may have discovered love.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTMyNzg2NzgxNV5BMl5BanBnXkFtZTcwMTcxNzczNA@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:  [
         {
        Source: "Internet Movie Database",
        Value: "7.1/10", },
        {Source: "Rotten Tomatoes",
        Value: "96%",
         },{
        Source: "Metacritic",
        Value: "81/100" ,},],
        Released: "15 Apr 1994",
        Response: "True",
        Runtime: "117 min",
        Title: "Four Weddings and a Funeral",
        Type: "movie",
        Website: "N/A",
        Writer: "Richard Curtis",
        Year: "1994",
        imdbID: "tt0109831",
        imdbRating: "7.1",
        imdbVotes: "145,815",
    },
    
    {
        Actors: "Nick Bateman, Caitlin Carver, Tyler Johnson",
        Awards: "N/A",
        BoxOffice: "N/A",
        Country: "United States",
        DVD: "N/A",
        Director: "Tosca Musk",
        Genre: "Comedy, Romance",
        Language: "English",
        Metascore: "N/A",
        Plot: "After a career-ending accident, former NFL recruit Ian Hunter is back on campus-and he's ready to get his new game on.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNTZlODAxN2EtMWZiOC00NDY4LTk4YjQtMGE4YzI2MTVmM2M0XkEyXkFqcGdeQXVyMjIwNDcwMTU@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "N/A",
        Ratings: [
        {
        Source: "Internet Movie Database",
        Value: "6.4/10" ,},],
        Released: "15 Mar 2018",
        Response: "True",
        Runtime: "89 min",
        Title: "The Matchmaker's Playbook",
        Type: "movie",
        Website: "N/A",
        Writer: "Joany Kane, Rachel Van Dyken",
        Year: "2018",
        imdbID: "tt7913934",
        imdbRating: "6.4",
        imdbVotes: "1,538",
    },
    
    {
        Actors: "Jude Law, Carrie Coon, Oona Roche",
        Awards: "5 wins & 22 nominations",
        BoxOffice: "$137,886",
        Country: "United Kingdom, Canada",
        DVD: "17 Nov 2020",
        Director: "Sean Durkin",
        Genre: "Drama, Romance",
        Language: "English",
        Metascore: "80",
        Plot: "Life for an entrepreneur and his American family begins to take a twisted turn after moving into an English country manor.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMGRjYzI5ZGUtZGJjYy00ZTYyLWJlNzItNWM0MDc0ZDVmM2IwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:  [
            {
        Source: "Internet Movie Database",
        Value: "6.3/10" ,},
       { Source: "Rotten Tomatoes",
        Value: "89%",
         },{
        Source: "Metacritic",
        Value: "80/100" ,},],
        Released: "18 Sep 2020",
        Response: "True",
        Runtime: "107 min",
        Title: "The Nest",
        Type: "movie",
        Website: "N/A",
        Writer: "Sean Durkin",
        Year: "2020",
        imdbID: "tt8338762",
        imdbRating: "6.3",
        imdbVotes: "10,017",
        
    },
    ///8
    {
        Actors: "Lily James, Amanda Seyfried, Meryl Streep",
        Awards: "12 nominations",
        BoxOffice: "$120,634,935",
        Country: "United Kingdom, United States, Japan",
        DVD: "23 Oct 2018",
        Director: "Ol Parker",
        Genre: "Comedy, Musical, Romance",
        Language: "English, French, Greek",
        Metascore: "60",
        Plot: "Five years after the events of Mamma Mia! (2008), Sophie prepares for the grand reopening of the Hotel Bella Donna as she learns more about her mother's past.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjEwMTM3OTI1NV5BMl5BanBnXkFtZTgwNDk5NTY0NTM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings:  [ 
        {Source: "Internet Movie Database",
        Value: "6.6/10",
         },
        {Source: "Rotten Tomatoes",
        Value: "79%",
         },{
        Source: "Metacritic",
        Value: "60/100" ,},],
        Released: "20 Jul 2018",
        Response: "True",
        Runtime: "114 min",
        Title: "Mamma Mia! Here We Go Again",
        Type: "movie",
        Website: "N/A",
        Writer: "Ol Parker, Richard Curtis, Catherine Johnson",
        Year: "2018",
        imdbID: "tt6911608",
        imdbRating: "6.6",
        imdbVotes: "86,753",
    },
    ///9
    {
        Actors: "Tom Cruise, Penélope Cruz, Cameron Diaz",
        Awards: "Nominated for 1 Oscar. 5 wins & 34 nominations total",
        BoxOffice: "$100,618,344",
        Country: "United States, Spain",
        DVD: "21 May 2002",
        Director: "Cameron Crowe",
        Genre: "Fantasy, Mystery, Romance",
        Language: "English, Spanish",
        Metascore: "45",
        Plot: "A self-indulgent and vain publishing magnate finds his privileged life upended after a vehicular accident with a resentful lover.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYzFlMTJjYzUtMWFjYy00NjkyLTg1Y2EtYmZkMjdlOGQ1ZGYwL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
         {
        Source: "Internet Movie Database",
        Value: "6.9/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "42%",
         },{
        Source: "Metacritic",
        Value: "45/100" ,},],
        Released: "14 Dec 2001",
        Response: "True",
        Runtime: "136 min",
        Title: "Vanilla Sky",
        Type: "movie",
        Website: "N/A",
        Writer: "Alejandro Amenábar, Mateo Gil, Cameron Crowe",
        Year: "2001",
        imdbID: "tt0259711",
        imdbRating: "6.9",
        imdbVotes: "255,507"
    },

    
    {
        Actors: "Christian Slater, Patricia Arquette, Dennis Hopper",
        Awards: "1 win & 10 nominations",
        BoxOffice: "$12,281,551",
        Country: "United States, France",
        DVD: "15 May 2007",
        Director: "Tony Scott",
        Genre: "Crime, Drama, Romance",
        Language: "English, Italian",
        Metascore: "59",
        Plot: "In Detroit, a lonely pop culture geek marries a call girl, steals cocaine from her pimp, and tries to sell it in Hollywood. Meanwhile, the owners of the cocaine, the Mob, track them down in an attempt to reclaim it.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYWRhYWJjNGEtMjNhNi00NzFkLTk1ZGUtNjNmM2FlNTNhNWRjXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: 
        [
{        Source: "Internet Movie Database",
        Value: "7.9/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "93%",
         },{
        Source: "Metacritic",
        Value: "59/100" },],
        Released: "10 Sep 1993",
        Response: "True",
        Runtime: "119 min",
        Title: "True Romance",
        Type: "movie",
        Website: "N/A",
        Writer: "Quentin Tarantino, Roger Avary",
        Year: "1993",
        imdbID: "tt0108399",
        imdbRating: "7.9",
        imdbVotes: "216,724",
    },

    
    {
        Actors: "Robert De Niro, Chazz Palminteri, Lillo Brancato",
        Awards: "1 win & 3 nominations",
        BoxOffice: "$17,287,898",
        Country: "United States",
        DVD: "11 Jan 2010",
        Director: "Robert De Niro",
        Genre: "Crime, Drama",
        Language: "English, Italian",
        Metascore: "80",
        Plot: "A father becomes worried when a local gangster befriends his son in the Bronx in the 1960s.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTczOTczNjE3Ml5BMl5BanBnXkFtZTgwODEzMzg5MTI@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [ 
        {Source: "Internet Movie Database",
        Value: "7.8/10",
         },{
        Source: "Rotten Tomatoes",
        Value: "97%",
         },{
        Source: "Metacritic",
        Value: "80/100" ,},],
        Released: "01 Oct 1993",
        Response: "True",
        Runtime: "121 min",
        Title: "A Bronx Tale",
        Type: "movie",
        Website: "N/A",
        Writer: "Chazz Palminteri",
        Year: "1993",
        imdbID: "tt0106489",
        imdbRating: "7.8",
        imdbVotes: "134,408",
    },

    
]