export const HorrorMovieDatabase = [
     {
        Actors: "Bob Odenkirk, Aleksey Serebryakov, Connie Nielsen",
        Awards: "1 win & 2 nominations",
        BoxOffice: "$27,268,035",
        Country: "United States, Japan",
        DVD: "15 Apr 2021",
        Director: "Ilya Naishuller",
        Genre: "Action, Crime, Drama",
        Language: "English, Russian, Spanish",
        Metascore: "64",
        Plot: "A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjM5YTRlZmUtZGVmYi00ZjE2LWIyNzAtOWVhMDk1MDdkYzhjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "7.4/10" },
        {Source: "Rotten Tomatoes",
        Value: "84%",
         },{
        Source: "Metacritic",
        Value: "64/100" ,},],
        Released: "26 Mar 2021",
        Response: "True",
        Runtime: "92 min",
        Title: "Nobody",
        Type: "movie",
        Website: "N/A",
        Writer: "Derek Kolstad",
        Year: "2021",
        imdbID: "tt7888964",
        imdbRating: "7.4",
        imdbVotes: "159,241",
     },
////1
     {
        Actors: "Carey Mulligan, Bo Burnham, Alison Brie",
        Awards: "Won 1 Oscar. 110 wins & 169 nominations total",
        BoxOffice: "$6,460,965",
        Country: "United Kingdom, United States",
        DVD: "15 Jan 2021",
        Director: "Emerald Fennell",
        Genre: "Crime, Drama, Thriller",
        Language: "English",
        Metascore: "73",
        Plot: "A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who crossed her path.",
        Poster: "https://m.media-amazon.com/images/M/MV5BOTgzMzE4MGItZDgxYS00ZGEwLWE3YTctZWY3ZDAyMTk0ZGU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
        {Source: "Internet Movie Database",
        Value: "7.5/10",
         },{
        Source: "Rotten Tomatoes",
        Value: "90%",
         },{
        Source: "Metacritic",
        Value: "73/100" ,}],
        Released: "25 Dec 2020",
        Response: "True",
        Runtime: "113 min",
        Title: "Promising Young Woman",
        Type: "movie",
        Website: "N/A",
        Writer: "Emerald Fennell",
        Year: "2020",
        imdbID: "tt9620292",
        imdbRating: "7.5",
        imdbVotes: "125,861",
    },


    {
        Actors: "Anthony Hopkins, Olivia Colman, Mark Gatiss",
        Awards: "Won 2 Oscars. 26 wins & 135 nominations total",
        BoxOffice: "$2,122,771",
        Country: "United Kingdom, France",
        DVD: "25 Mar 2021",
        Director: "Florian Zeller",
        Genre: "Drama",
        Language: "English",
        Metascore: "88",
        Plot: "A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.",
        Poster: "https://m.media-amazon.com/images/M/MV5BZGJhNWRiOWQtMjI4OS00ZjcxLTgwMTAtMzQ2ODkxY2JkOTVlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
         {
        Source: "Internet Movie Database",
        Value: "8.3/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "98%",
         },{
        Source: "Metacritic",
        Value: "88/100" ,},],
        Released: "26 Feb 2021",
        Response: "True",
        Runtime: "97 min",
        Title: "The Father",
        Type: "movie",
        Website: "N/A",
        Writer: "Christopher Hampton, Florian Zeller",
        Year: "2020",
        imdbID: "tt10272386",
        imdbRating: "8.3",
        imdbVotes: "96,269"
    },
    
    {
        Actors: "Frances McDormand, David Strathairn, Linda May",
        Awards: "Won 3 Oscars. 233 wins & 139 nominations total",
        BoxOffice: "$2,143,000",
        Country: "United States",
        DVD: "19 Feb 2021",
        Director: "Chloé Zhao",
        Genre: "Drama",
        Language: "English",
        Metascore: "93",
        Plot: "A woman in her sixties, after losing everything in the Great Recession, embarks on a journey through the American West, living as a van-dwelling modern-day nomad.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMDRiZWUxNmItNDU5Yy00ODNmLTk0M2ItZjQzZTA5OTJkZjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "7.4/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "93%",
         },{
        Source: "Metacritic",
        Value: "93/100",}, ],
        Released: "19 Feb 2021",
        Response: "True",
        Runtime: "107 min",
        Title: "Nomadland",
        Type: "movie",
        Website: "N/A",
        Writer: "Chloé Zhao, Jessica Bruder",
        Year: "2020",
        imdbID: "tt9770150",
        imdbRating: "7.4",
        imdbVotes: "126,127",
    },
    
    {
        Actors: "Riz Ahmed, Olivia Cooke, Paul Raci",
        Awards: "Won 2 Oscars. 82 wins & 163 nominations total",
        BoxOffice: "N/A",
        Country: "United States",
        DVD: "N/A",
        Director: "Darius Marder",
        Genre: "Drama, Music",
        Language: "English, American Sign , French",
        Metascore: "82",
        Plot: "A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNjcyYjg0M2ItMzMyZS00NmM1LTlhZDMtN2MxN2RhNWY4YTkwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
        Production: "Caviar",
        Rated: "R",
        Ratings:
        [
            {
        Source: "Internet Movie Database",
        Value: "7.8/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "97%",
         },{
        Source: "Metacritic",
        Value: "82/100" ,},],
        Released: "04 Dec 2020",
        Response: "True",
        Runtime: "120 min",
        Title: "Sound of Metal",
        Type: "movie",
        Website: "N/A",
        Writer: "Darius Marder, Abraham Marder, Derek Cianfrance",
        Year: "2019",
        imdbID: "tt5363618",
        imdbRating: "7.8",
        imdbVotes: "104,647",
    },
    
    {
        Actors: "Angelina Jolie, Nicholas Hoult, Finn Little",
        Awards: "N/A",
        BoxOffice: "$7,347,103",
        Country: "Canada, United States",
        DVD: "14 May 2021",
        Director: "Taylor Sheridan",
        Genre: "Action, Crime, Drama",
        Language: "English",
        Metascore: "59",
        Plot: "A teenage murder witness finds himself pursued by twin assassins in the Montana wilderness with a survival expert tasked with protecting him -- and a forest fire threatening to consume them all.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMDAxMmQ0NTAtNDllNC00ZjE2LTlkNjUtMmExNmY0MmNkMDQ0XkEyXkFqcGdeQXVyNzYyOTM1ODI@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "6.0/10" },
        {Source: "Rotten Tomatoes",
        Value: "61%",
         },{
        Source: "Metacritic",
        Value: "59/100" ,},],
        Released: "14 May 2021",
        Response: "True",
        Runtime: "100 min",
        Title: "Those Who Wish Me Dead",
        Type: "movie",
        Website: "N/A",
        Writer: "Michael Koryta, Charles Leavitt, Taylor Sheridan",
        Year: "2021",
        imdbID: "tt3215824",
        imdbRating: "6.0",
        imdbVotes: "45,132",
    },
    ///6
    {
        Actors: "Sebastian Stan, Denise Gough, Yorgos Pirpassopoulos",
        Awards: "N/A",
        BoxOffice: "$30,932",
        Country: "United Kingdom, United States, Greece",
        DVD: "16 Apr 2021",
        Director: "Argyris Papadimitropoulos",
        Genre: "Drama, Romance",
        Language: "English, Greek",
        Metascore: "58",
        Plot: "A spark on a Friday can lead to a sizzling weekend fling, but what happens when you get to the inevitable Monday?",
        Poster: "https://m.media-amazon.com/images/M/MV5BYTg4NWQ4ODEtMmQ3Zi00N2JlLTgzNDEtMDMzYjNkODUzODE5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: 
      [{
        Source: "Internet Movie Database",
        Value: "6.1/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "50%",
         },{
        Source: "Metacritic",
        Value: "58/100" ,},],
        Released: "16 Apr 2021",
        Response: "True",
        Runtime: "116 min",
        Title: "Monday",
        Type: "movie",
        Website: "N/A",
        Writer: "Rob Hayes, Argyris Papadimitropoulos",
        Year: "2020",
        imdbID: "tt8884906",
        imdbRating: "6.1",
        imdbVotes: "2,991",
    },
    
    {
        Actors: "Robert De Niro, Kevin Bacon, Brad Pitt",
        Awards: "Nominated for 1 Oscar. 1 win & 5 nominations total",
        BoxOffice: "$53,315,285",
        Country: "United States",
        DVD: "03 Nov 2009",
        Director: "Barry Levinson",
        Genre: "Crime, Drama, Thriller",
        Language: "English",
        Metascore: "49",
        Plot: "After a prank goes disastrously wrong, a group of boys are sent to a detention center where they are brutalized. Thirteen years later, an unexpected random encounter with a former guard gives them a chance for revenge.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMzk1MmI4NzAtOGRiNS00YjY1LTllNmEtZDhiZDM4MjU2NTMxXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "7.6/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "73%",
         },{
        Source: "Metacritic",
        Value: "49/100" ,},],
        Released: "18 Oct 1996",
        Response: "True",
        Runtime: "147 min",
        Title: "Sleepers",
        Type: "movie",
        Website: "N/A",
        Writer: "Lorenzo Carcaterra, Barry Levinson",
        Year: "1996",
        imdbID: "tt0117665",
        imdbRating: "7.6",
        imdbVotes: "207,493",
    },
    
    {
        Actors: "Idris Elba, Caleb McLaughlin, Lorraine Toussaint",
Awards: "1 win",
BoxOffice: "N/A",
Country: "United Kingdom, United States",
DVD: "02 Apr 2021",
Director: "Ricky Staub",
Genre: "Drama",
Language: "English",
Metascore: "67",
Plot: "Sent to live with his estranged father for the summer, a rebellious teen finds kinship in a tight-knit Philadelphia community of Black cowboys.",
Poster: "https://m.media-amazon.com/images/M/MV5BODRlNjNhNDctMTJjYS00Y2Q4LTk1MGEtYTdiMDlkYWNkNGFjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
Production: "N/A",
Rated: "R",
Ratings: [
{
Source: "Internet Movie Database",
Value: "6.3/10" ,},
{Source: "Rotten Tomatoes",
Value: "80%",
 },{
Source: "Metacritic",
Value: "67/100" ,},],
Released: "02 Apr 2021",
Response: "True",
Runtime: "111 min",
Title: "Concrete Cowboy",
Type: "movie",
Website: "N/A",
Writer: "G. Neri, Ricky Staub, Dan Walser",
Year: "2020",
imdbID: "tt8846176",
imdbRating: "6.3",
imdbVotes: "7,480",
    },
    /////9
    {
        Actors: "Tae-goo Eom, Jeon Yeo-bin, Seung-Won Cha",
        Awards: "6 nominations",
        BoxOffice: "N/A",
        Country: "South Korea",
        DVD: "09 Apr 2021",
        Director: "Park Hoon-jung",
        Genre: "Action, Crime, Drama",
        Language: "Korean",
        Metascore: "59",
        Plot: "Hiding out in Jeju Island following a brutal tragedy, a wronged mobster with a target on his back connects with a woman who has her own demons.",
        Poster: "https://m.media-amazon.com/images/M/MV5BOTA1MzFkYzYtMjMzNC00MDQzLTg4NDgtOWJjMzliOGMzODFlXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
        Production: "N/A",
        Rated: "TV-MA",
        Ratings: [
            {
        Source: "Internet Movie Database",
        Value: "6.7/10" },
        {Source: "Rotten Tomatoes",
        Value: "72%",
         },{
        Source: "Metacritic",
        Value: "59/100" ,},],
        Released: "09 Apr 2021",
        Response: "True",
        Runtime: "131 min",
        Title: "Night in Paradise",
        Type: "movie",
        Website: "N/A",
        Writer: "Park Hoon-jung",
        Year: "2020",
        imdbID: "tt12792418",
        imdbRating: "6.7",
        imdbVotes: "5,221",
    },
    
    ]