export const TopRatedMoviesDatabase =[

    {
        Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
        Awards: "Nominated for 7 Oscars. 21 wins & 43 nominations total",
        BoxOffice: "$28,699,976",
        Country: "United States",
        DVD: "21 Dec 1999",
        Director: "Frank Darabont",
        Genre: "Drama",
        Language: "English",
        Metascore: "80",
        Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:  [ 
        {Source: "Internet Movie Database",
        Value: "9.3/10",
         },{Source: "Rotten Tomatoes",
        Value: "91%",
         },{
        Source: "Metacritic",
        Value: "80/100" ,},],
        Released: "14 Oct 1994",
        Response: "True",
        Runtime: "142 min",
        Title: "The Shawshank Redemption",
        Type: "movie",
        Website: "N/A",
        Writer: "Stephen King, Frank Darabont",
        Year: "1994",
        imdbID: "tt0111161",
        imdbRating: "9.3",
        imdbVotes: "2,470,325",

    },

    {
        Actors: "Marlon Brando, Al Pacino, James Caan",
        Awards: "Won 3 Oscars. 31 wins & 30 nominations total",
        BoxOffice: "$134,966,411",
        Country: "United States",
        DVD: "11 May 2004",
        Director: "Francis Ford Coppola",
        Genre: "Crime, Drama",
        Language: "English, Italian, Latin",
        Metascore: "100",
        Plot: "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
        Poster: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [{
        Source: "Internet Movie Database",
        Value: "9.2/10" },
        {Source: "Rotten Tomatoes",
        Value: "97%",
         },{
        Source: "Metacritic",
        Value: "100/100" ,}],
        Released: "24 Mar 1972",
        Response: "True",
        Runtime: "175 min",
        Title: "The Godfather",
        Type: "movie",
        Website: "N/A",
        Writer: "Mario Puzo, Francis Ford Coppola",
        Year: "1972",
        imdbID: "tt0068646",
        imdbRating: "9.2",
        imdbVotes: "1,702,906",
    },

  //array 2
    {
        Actors: "Joaquin Phoenix, Rooney Mara, Sia",
        Awards: "15 wins",
        BoxOffice: "N/A",
        Country: "Australia",
        DVD: "N/A",
        Director: "Chris Delforce",
        Genre: "Documentary",
        Language: "English",
        Metascore: "N/A",
        Plot: "Dominion uses drones, hidden and handheld cameras to expose the dark underbelly of modern animal agriculture, questioning the morality and validity of humankind's dominion over the animal kingdom.",
        Poster: "https://m.media-amazon.com/images/M/MV5BOWMyNzExNzctOWNjNy00MzMxLWJlYWMtYjJiYmM0Mjg0YWZmXkEyXkFqcGdeQXVyNTU5NjAwMTQ@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "N/A",
        Ratings: [
       { Source: "Internet Movie Database",
        Value: "9.1/10",} ,],
        Released: "10 Jun 2018",
        Response: "True",
        Runtime: "120 min",
        Title: "Dominion",
        Type: "movie",
        Website: "N/A",
        Writer: "Chris Delforce",
        Year: "2018",
        imdbID: "tt5773402",
        imdbRating: "9.1",
        imdbVotes: "3,067",
    },
//ar 3
    {
        Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
        Awards: "Won 2 Oscars. 159 wins & 163 nominations total",
        BoxOffice: "$534,858,444",
        Country: "United States, United Kingdom",
        DVD: "09 Dec 2008",
        Director: "Christopher Nolan",
        Genre: "Action, Crime, Drama",
        Language: "English, Mandarin",
        Metascore: "84",
        Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
        {Source: "Internet Movie Database",
        Value: "9.0/10",
         },
         {
        Source: "Rotten Tomatoes",
        Value: "94%",
         },{
        Source: "Metacritic",
        Value: "84/100",},],
        Released: "18 Jul 2008",
        Response: "True",
        Runtime: "152 min",
        Title: "The Dark Knight",
        Type: "movie",
        Website: "N/A",
        Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
        Year: "2008",
        imdbID: "tt0468569",
        imdbRating: "9.0",
        imdbVotes: "2,417,442",
    },

    {
Actors: "Al Pacino, Robert De Niro, Robert Duvall",
Awards: "Won 6 Oscars. 17 wins & 20 nominations total",
BoxOffice: "$47,834,595",
Country: "United States",
DVD: "24 May 2005",
Director: "Francis Ford Coppola",
Genre: "Crime, Drama",
Language: "English, Italian, Spanish, Latin, Sicilian",
Metascore: "90",
Plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
Poster: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
Production: "N/A",
Rated: "R",
Ratings:  [
    {
Source: "Internet Movie Database",
Value: "9.0/10", },
{Source: "Rotten Tomatoes",
Value: "96%",
 },
 {
Source: "Metacritic",
Value: "90/100" ,},],
Released: "18 Dec 1974",
Response: "True",
Runtime: "202 min",
Title: "The Godfather: Part II",
Type: "movie",
Website: "N/A",
Writer: "Francis Ford Coppola, Mario Puzo",
Year: "1974",
imdbID: "tt0071562",
imdbRating: "9.0",
imdbVotes: "1,182,910",
    },
    //ara -5
    {
        Actors: "David Attenborough, Max Hughes",
        Awards: "Won 3 Primetime Emmys. 6 wins & 8 nominations total",
        BoxOffice: "N/A",
        Country: "United Kingdom",
        DVD: "04 Oct 2020",
        Director: "Alastair Fothergill, Jonathan Hughes, Keith Scholey",
        Genre: "Documentary, Biography",
        Language: "English",
        Metascore: "72",
        Plot: "One man has seen more of the natural world than any other. This unique feature documentary is his witness statement.",
        Poster: "https://m.media-amazon.com/images/M/MV5BY2FkMjE0ZDgtNWQxZS00NmZiLWEwMDYtMjE5M2RmOTZiODk5XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG",
        Ratings: [
         {
        Source: "Internet Movie Database",
        Value: "9.0/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "95%",
         },{
        Source: "Metacritic",
        Value: "72/100" ,},],
        Released: "04 Oct 2020",
        Response: "True",
        Runtime: "83 min",
        Title: "David Attenborough: A Life on Our Planet",
        Type: "movie",
        Website: "N/A",
        Writer: "N/A",
        Year: "2020",
        imdbID: "tt11989890",
        imdbRating: "9.0",
        imdbVotes: "29,322",
    },


    {
Actors: "Radha Bessy, Subba Rao Vepada, Praneeta Patnaik",
Awards: "1 win & 6 nominations",
BoxOffice: "N/A",
Country: "India",
DVD: "06 Sep 2019",
Director: "Venkatesh Maha",
Genre: "Drama",
Language: "Telugu",
Metascore: "N/A",
Plot: "Four unconventional love stories set in the town and including the people of Kancherapalem.",
Poster: "https://m.media-amazon.com/images/M/MV5BYjg2YWM0YzUtODViNS00OWRkLWI0YmItNDdhODUwMjVhYjQ1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
Production: "Suresh Productions, Paruchuri Vijaya Praveena Arts",
Rated: "N/A",
Ratings: [
 {
Source: "Internet Movie Database",
Value: "8.9/10" ,},],
Released: "06 Sep 2018",
Response: "True",
Runtime: "152 min",
Title: "C/o Kancharapalem",
Type: "movie",
Website: "N/A",
Writer: "Venkatesh Maha",
Year: "2018",
imdbID: "tt7391996",
imdbRating: "8.9",
imdbVotes: "5,937",
    },

    //ar =7
    {
        Actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
        Awards: "Won 1 Oscar. 70 wins & 75 nominations total",
        BoxOffice: "$107,928,762",
        Country: "United States",
        DVD: "20 Aug 2002",
        Director: "Quentin Tarantino",
        Genre: "Crime, Drama",
        Language: "English, Spanish, French",
        Metascore: "94",
        Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
        {
        Source: "Internet Movie Database",
        Value: "8.9/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "92%",
         },{
        Source: "Metacritic",
        Value: "94/100" ,},],
        Released: "14 Oct 1994",
        Response: "True",
        Runtime: "154 min",
        Title: "Pulp Fiction",
        Type: "movie",
        Website: "N/A",
        Writer: "Quentin Tarantino, Roger Avary",
        Year: "1994",
        imdbID: "tt0110912",
        imdbRating: "8.9",
        imdbVotes: "1,907,435",
    },

    {
Actors: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
Awards: "Won 7 Oscars. 91 wins & 49 nominations total",
BoxOffice: "$96,898,818",
Country: "United States",
DVD: "12 Feb 2008",
Director: "Steven Spielberg",
Genre: "Biography, Drama, History",
Language: "English, Hebrew, German, Polish, Latin",
Metascore: "94",
Plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
Poster: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
Production: "N/A",
Rated: "R",
Ratings: [{
Source: "Internet Movie Database",
Value: "8.9/10" ,},
{Source: "Rotten Tomatoes",
Value: "98%",
},{
Source: "Metacritic",
Value: "94/100" ,},],
Released: "04 Feb 1994",
Response: "True",
Runtime: "195 min",
Title: "Schindler's List",
Type: "movie",
Website: "N/A",
Writer: "Thomas Keneally, Steven Zaillian",
Year: "1993",
imdbID: "tt0108052",
imdbRating: "8.9",
imdbVotes: "1,265,606",
    },
    //ar=9
    {
        Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
        Awards: "Won 11 Oscars. 209 wins & 124 nominations total",
        BoxOffice: "$377,845,905",
        Country: "New Zealand, United States",
        DVD: "25 May 2004",
        Director: "Peter Jackson",
        Genre: "Action, Adventure, Drama",
        Language: "English, Quenya, Old English, Sindarin",
        Metascore: "94",
        Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
         {
        Source: "Internet Movie Database",
        Value: "8.9/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "93%",
         },
         {
        Source: "Metacritic",
        Value: "94/100" ,},],
        Released: "17 Dec 2003",
        Response: "True",
        Runtime: "201 min",
        Title: "The Lord of the Rings: The Return of the King",
        Type: "movie",
        Website: "N/A",
        Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
        Year: "2003",
        imdbID: "tt0167260",
        imdbRating: "8.9",
        imdbVotes: "1,708,689",
    },
    //a-10
    {
        Actors: "Kareem Abdul-Jabbar, Mike Albanese, Muhammad Ali",
        Awards: "Won 1 Oscar. 48 wins & 35 nominations total",
        BoxOffice: "N/A",
        Country: "United States",
        DVD: "N/A",
        Director: "Ezra Edelman",
        Genre: "Documentary, Biography, Crime",
        Language: "English",
        Metascore: "N/A",
        Plot: "A chronicle of the rise and fall of O.J. Simpson, whose high-profile murder trial exposed the extent of American racial tensions, revealing a fractured and divided nation.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNGNmYmY3OTktMWM1Ni00NTU1LTk0ZjctMDcwYjViMjY0MTIwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "TV-MA",
        Ratings:  [ 
        {Source: "Internet Movie Database",
        Value: "8.9/10",
         },{
        Source: "Rotten Tomatoes",
        Value: "100%" ,},],
        Released: "04 Aug 2016",
        Response: "True",
        Runtime: "467 min",
        Title: "O.J.: Made in America",
        Type: "movie",
        Website: "N/A",
        Writer: "N/A",
        Year: "2016",
        imdbID: "tt5275892",
        imdbRating: "8.9",
        imdbVotes: "18,691",
    },
    //arr 11
    {
        Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
Awards: "Won 4 Oscars. 157 wins & 220 nominations total",
BoxOffice: "$292,576,195",
Country: "United States, United Kingdom",
DVD: "07 Dec 2010",
Director: "Christopher Nolan",
Genre: "Action, Adventure, Sci-Fi",
Language: "English, Japanese, French",
Metascore: "74",
Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
Poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
Production: "N/A",
Rated: "PG-13",
Ratings: [
{
Source: "Internet Movie Database",
Value: "8.8/10" ,},
{Source: "Rotten Tomatoes",
Value: "87%",
 },{
Source: "Metacritic",
Value: "74/100" ,},],
Released: "16 Jul 2010",
Response: "True",
Runtime: "148 min",
Title: "Inception",
Type: "movie",
Website: "N/A",
Writer: "Christopher Nolan",
Year: "2010",
imdbID: "tt1375666",
imdbRating: "8.8",
imdbVotes: "2,168,803",
    }
   
]