export const popularMovieDataBase = [
    {
        Actors: "D.B. Sweeney, Moira Kelly, Roy Dotrice",
        Awards: "N/A",
        BoxOffice: "$25,105,517",
        Country: "United States",
        DVD: "07 Oct 2004",
        Director: "Paul Michael Glaser",
        Genre: "Comedy, Drama, Romance",
        Language: "English, French, Russian",
        Metascore: "53",
        Plot: "A temperamental figure skater and a former hockey player try to win Olympic gold as a figure skating pairs team.",
        Poster: "https://m.media-amazon.com/images/M/MV5BZTAzZDIyMzctMzNhZC00ZjI0LWJhMTMtODBiODNhOTA3ZDQ4XkEyXkFqcGdeQXVyNjMwMjk0MTQ@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG",
        Ratings: [
  {

     Source: "Internet Movie Database",
     Value: "6.9/10",
 },
 
{

    Source: "Rotten Tomatoes",
    Value: "57%"
},
 
{

    Source: "Metacritic",
    Value: "53/100"
     
}],
 
        Released: "27 Mar 1992",
        Response: "True",
        Runtime: "101 min",
        Title: "The Cutting Edge",
        Type: "movie",
        Website: "N/A",
        Writer: "Tony Gilroy",
        Year: "1992",
        imdbID: "tt0104040",
        imdbRating: "6.9",
        imdbVotes: "19,499",
        },
    
        {
        Actors: "Frank Gingerich, Morgan Gingerich, Annette O'Toole",
        Awards: "2 nominations",
        BoxOffice: "N/A",
        Country: "United States",
        DVD: "26 Jan 2018",
        Director: "David Wain",
        Genre: "Biography, Comedy",
        Language: "English",
        Metascore: "55",
        Plot: "In the 1970s and '80s, National Lampoon's success and influence creates a new media empire overseen in part by the brilliant and troubled Douglas Kenney.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTg3OTQyODAwOF5BMl5BanBnXkFtZTgwMDY1MDM0NDM@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "TV-MA",
        Ratings:  [
        {

            Source: "Internet Movie Database",
            Value: "6.8/10",
        },

        {

            Source: "Rotten Tomatoes",
            Value: "67%",
        },
        {

            Source: "Metacritic",
            Value: "55/100",
        }],
        
        Released: "26 Jan 2018",
        Response: "True",
        Runtime: "101 min",
        Title: "A Futile and Stupid Gesture",
        Type: "movie",
        Website: "N/A",
        Writer: "Michael Colton, John Aboud, Josh Karp",
        Year: "2018",
        imdbID: "tt5566790",
        imdbRating: "6.8",
        imdbVotes: "14,953",
    },
    
    {
        Actors: "Marie-Laure Dougnac, Dominique Pinon, Pascal Benezech",
        Awards: "15 wins & 16 nominations total",
        BoxOffice: "$1,794,187",
        Country: "France",
        DVD: "26 Aug 2008",
        Director: "Marc Caro, Jean-Pierre Jeunet",
        Genre: "Comedy, Crime",
        Language: "French",
        Metascore: "66",
        Plot: "Post-apocalyptic surrealist black comedy about the landlord of an apartment building who occasionally prepares a delicacy for his odd tenants.",
        Poster: "https://m.media-amazon.com/images/M/MV5BNjg5ZDM0MTEtYTZmNC00NDJiLWI5MTktYzk4N2QxY2IxZTc2L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings: [
     {   Source: "Internet Movie Database",
        Value: "7.6/10",
    },
     {   Source: "Rotten Tomatoes",
        Value: "89%",
    },
     
    {   Source: "Metacritic",
        Value: "66/100",
    },],
        Released: "03 Apr 1992",
        Response: "True",
        Runtime: "99 min",
        Title: "Delicatessen",
        Type: "movie",
        Website: "N/A",
        Writer: "Jean-Pierre Jeunet, Marc Caro, Gilles Adrien",
        Year: "1991",
        imdbID: "tt0101700",
        imdbRating: "7.6",
        imdbVotes: "83,046",
    },
    // array4
    { 
 Actors: "María Mercedes Coroy, Sabrina De La Hoz, Margarita Kenéfic",
Awards: "23 wins & 61 nominations",
BoxOffice: "N/A",
Country: "Guatemala, France",
DVD: "06 Aug 2020",
Director: "Jayro Bustamante",
Genre: "Crime, Drama, Horror",
Language: "Spanish, Maya",
Metascore: "79",
Plot: "An aging paranoid war criminal, protected by his faithful wife, faces death while being haunted by the ghosts of his past.",
Poster: "https://m.media-amazon.com/images/M/MV5BNjE5NDM4OWEtOTEyMy00MmM0LTkxYzEtMDFhYjk3M2FlMzQzXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
Production: "N/A",
Rated: "Not Rated",
Ratings: [{
Source: "Internet Movie Database",
Value: "6.6/10" ,
    },
{
Source: "Rotten Tomatoes",
Value: "96%",},{
Source: "Metacritic",
Value: "79/100",},],
Released: "06 Aug 2020",
Response: "True",
Runtime: "97 min",
Title: "La llorona",
Type: "movie",
Website: "N/A",
Writer: "Jayro Bustamante, Lisandro Sanchez",
Year: "2019",
imdbID: "tt10767168",
imdbRating: "6.6",
imdbVotes: "5,052",
    },
    //arr5
    {
 Actors: "Clint Eastwood, Sondra Locke, Geoffrey Lewis",
Awards: "1 win & 4 nominations",
BoxOffice: "$85,196,485",
Country: "United States",
DVD: "02 Sep 2008",
Director: "James Fargo",
Genre: "Action, Comedy",
Language: "English",
Metascore: "41",
Plot: "The San Fernando Valley adventures of trucker turned prize-fighter Philo Beddoe and his pet orangutan Clyde.",
Poster: "https://m.media-amazon.com/images/M/MV5BNjFiNGZmNTktZTExZS00NzhlLWJjNTAtM2JlY2ZhNmI2N2YxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg",
Production: "Warner Bros.",
Rated: "PG",
Ratings: [ 
{Source: "Internet Movie Database",
Value: "6.3/10",
 }
,{Source: "Rotten Tomatoes",
Value: "37%" ,
},{
Source: "Metacritic",
Value: "41/100" ,}],
Released: "20 Dec 1978",
Response: "True",
Runtime: "114 min",
Title: "Every Which Way but Loose",
Type: "movie",
Website: "N/A",
Writer: "Jeremy Joe Kronsberg",
Year: "1978",
imdbID: "tt0077523",
imdbRating: "6.3",
imdbVotes: "25,846",
    },
     
    { 
Actors: "Dermot Mulroney, Sarah Jessica Parker, Claire Danes",
Awards: "4 wins & 8 nominations",
BoxOffice: "$60,062,868",
Country: "United States",
DVD: "02 May 2006",
Director: "Thomas Bezucha",
Genre: "Comedy, Drama, Romance",
Language: "English, American Sign ",
Metascore: "56",
Plot: "An uptight, conservative businesswoman accompanies her boyfriend to his eccentric and outgoing family's annual Christmas celebration and finds that she's a fish out of water in their free-spirited way of life.",
Poster: "https://m.media-amazon.com/images/M/MV5BNTkwMjM4MjMxMV5BMl5BanBnXkFtZTcwNjM1OTQzMQ@@._V1_SX300.jpg",
Production: "N/A",
Rated: "PG-13",
Ratings: [
{
Source: "Internet Movie Database",
Value: "6.3/10",},
{
Source: "Rotten Tomatoes",
Value: "53%",},
{
Source: "Metacritic",
Value: "56/100",}],
Released: "16 Dec 2005",
Response: "True",
Runtime: "103 min",
Title: "The Family Stone",
Type: "movie",
Website: "N/A",
Writer: "Thomas Bezucha",
Year: "2005",
imdbID: "tt0356680",
imdbRating: "6.3",
imdbVotes: "63,994",
    },
    //array 7
    {
        Actors: "Jamie Kennedy, Ryan O'Neal, Blair Underwood",
        Awards: "3 nominations",
        BoxOffice: "$34,432,201",
        Country: "United States",
        DVD: "18 Sep 2007",
        Director: "John Whitesell",
        Genre: "Comedy, Crime",
        Language: "English",
        Metascore: "43",
        Plot: "A senator arranges for his son, a rich white kid who fancies himself black, to be kidnapped by a couple of black actors pretending to be murderers to try and shock him out of his plans to become a rapper.",
        Poster: "https://m.media-amazon.com/images/M/MV5BODM3NzE0NTMxOF5BMl5BanBnXkFtZTYwMTIzNTk5._V1_SX300.jpg",
        Production: "N/A",
        Rated: "PG-13",
        Ratings: [
        {
        Source: "Internet Movie Database",
        Value: "5.2/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "31%",
        },{
        Source: "Metacritic",
        Value: "43/100" },],
        Released: "18 Apr 2003",
        Response: "True",
        Runtime: "86 min",
        Title: "Malibu's Most Wanted",
        Type: "movie",
        Website: "N/A",
        Writer: "Fax Bahr, Adam Small, Jamie Kennedy",
        Year: "2003",
        imdbID: "tt0328099",
        imdbRating: "5.2",
        imdbVotes: "19,126",
    },
    
    {
        Actors: "Ryan Phillippe, Barry Pepper, Joseph Cross",
        Awards: "Nominated for 2 Oscars. 16 wins & 28 nominations total",
        BoxOffice:"$33,602,376",
        Country: "United States",
        DVD: "06 Feb 2007",
        Director: "Clint Eastwood",
        Genre: "Action, Adventure, Drama",
        Language: "English",
        Metascore: "79",
        Plot: "The life stories of the six men who raised the flag at the Battle of Iwo Jima, a turning point in World War II.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTU2MjYxMjMyMF5BMl5BanBnXkFtZTYwMzAwMDc3._V1_SX300.jpg",
        Production: "N/A",
        Rated: "R",
        Ratings:  [
        {
        Source: "Internet Movie Database",
        Value: "7.1/10" ,},
        {Source: "Rotten Tomatoes",
        Value: "73%",
         },{
        Source: "Metacritic",
        Value: "79/100" }, 
    ],
        Released: "20 Oct 2006",
        Response: "True",
        Runtime: "135 min",
        Title: "Flags of Our Fathers",
        Type: "movie",
        Website: "N/A",
        Writer: "William Broyles Jr., Paul Haggis, James Bradley",
        Year: "2006",
        imdbID: "tt0418689",
        imdbRating: "7.1",
        imdbVotes: "120,625",
    },
    //array9
    {
Actors: "Steve Coogan, John C. Reilly, Shirley Henderson",
Awards: "6 wins & 30 nominations total",
BoxOffice: "$5,470,235",
Country: "United Kingdom, Canada, United States",
DVD: "26 Mar 2019",
Director: "Jon S. Baird",
Genre: "Biography, Comedy, Drama",
Language: "English",
Metascore: "75",
Plot: "Laurel and Hardy, the world's most famous comedy duo, attempt to reignite their film careers as they embark on what becomes their swan song - a grueling theatre tour of post-war Britain.",
Poster: "https://m.media-amazon.com/images/M/MV5BNjkzYjNiMWEtMTVhYy00N2JiLThhYWYtNmNkYTU1ZWE1ODBhXkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_SX300.jpg",
Production: "N/A",
Rated: "PG",
Ratings:  [
{Source: "Internet Movie Database",
Value: "7.2/10",
 },{
Source: "Rotten Tomatoes",
Value: "92%",
 },{
Source: "Metacritic",
Value: "75/100", },
],
Released: "11 Jan 2019",
Response: "True",
Runtime: "98 min",
Title: "Stan & Ollie",
Type: "movie",
Website: "N/A",
Writer: "Jeff Pope, 'A.J.' Marriot",
Year: "2018",
imdbID: "tt3385524",
imdbRating: "7.2",
imdbVotes: "35,081",
    },

    //array 10 
    {
Actors: "Noomi Rapace, Michael Nyqvist, Lena Endre",
Awards: "1 win & 4 nominations",
BoxOffice: "$7,638,241",
Country: "Sweden, Denmark, Germany",
DVD: "26 Oct 2010",
Director: "Daniel Alfredson",
Genre: "Action, Crime, Drama",
Language: "Swedish, Italian, English, French",
Metascore: "66",
Plot: "As computer hacker Lisbeth and journalist Mikael investigate a sex-trafficking ring, Lisbeth is accused of three murders, causing her to go on the run while Mikael works to clear her name.",
Poster: "https://m.media-amazon.com/images/M/MV5BMjI0MjIxMDIwNF5BMl5BanBnXkFtZTcwODk5MDc1Mw@@._V1_SX300.jpg",
Production: "N/A",
Rated: "R",
Ratings: [
    {
Source: "Internet Movie Database",
Value: "7.2/10",
 },{
Source: "Rotten Tomatoes",
Value: "69%"}
,{
Source: "Metacritic",
Value: "66/100" ,},],
Released: "27 Aug 2010",
Response: "True",
Runtime: "129 min",
Title: "Flickan som lekte med elden",
Type: "movie",
Website: "N/A",
Writer: "Jonas Frykberg, Stieg Larsson",
Year: "2009",
imdbID: "tt1216487",
imdbRating: "7.2",
imdbVotes: "93,159", 
    }
]
